# Generated by Django 4.0.3 on 2022-03-22 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movietitle', models.CharField(max_length=255)),
                ('movreleasedate', models.DateField()),
                ('movgenre', models.TextField()),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewdate', models.DateField()),
                ('review', models.TextField()),
                ('movieid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movrev.movie')),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
